kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-initdb-configmap
data:
  init.sql: | #script run on startup same as in db folder
    create database devopsroles;
    use devopsroles;

    CREATE TABLE test_table (
      name VARCHAR(20),
      color VARCHAR(10)
    );

    INSERT INTO test_table
      (name, color)
    VALUES
      ('dev', 'blue'),
      ('pro', 'yellow');
