kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-dynamic
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
